# Generated by Django 6.0.2 on 2026-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_batch_evaluation_provider_delete_testtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
