# Generated by Django 6.0.2 on 2026-02-17 23:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_provider_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
