# Generated by Django 6.0.2 on 2026-02-20 01:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_batch_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
