# Generated by Django 6.0.2 on 2026-03-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_batch_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('packed', 'Empacado'), ('sent', 'Enviado')], db_index=True, default='pending', max_length=16)),
                ('packed_at', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='dashboard.batch')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packing',
                'ordering': ['-updated_at'],
            },
        ),
    ]
